// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1zQy4vlLYPr_NHxIWklWpkclB0U1u4nA',
    appId: '1:568970626699:web:881f22415e0fd2e5fef68e',
    messagingSenderId: '568970626699',
    projectId: 'expense-tracker-6ac39',
    authDomain: 'expense-tracker-6ac39.firebaseapp.com',
    storageBucket: 'expense-tracker-6ac39.firebasestorage.app',
    measurementId: 'G-S2L6YKJWX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwIi7rBRMdR8HVwRNaaDXudwtYZ_vD2ls',
    appId: '1:568970626699:android:637e677c2b1d3de9fef68e',
    messagingSenderId: '568970626699',
    projectId: 'expense-tracker-6ac39',
    storageBucket: 'expense-tracker-6ac39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIbGypvFKUom603ZLmNSQsQ_WG4LhQhSc',
    appId: '1:568970626699:ios:5984ccad30cf8a0ffef68e',
    messagingSenderId: '568970626699',
    projectId: 'expense-tracker-6ac39',
    storageBucket: 'expense-tracker-6ac39.firebasestorage.app',
    iosClientId: '568970626699-nk6fsq13p1tjqvpk7pb7b8s1nm8ilp4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensesApp',
  );
}
